# Generated by Django 3.2.25 on 2025-12-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_assignment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='实际得分')),
                ('max_score', models.FloatField(default=100.0, help_text='满分')),
                ('comment', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignments.assignment')),
            ],
        ),
    ]
